<a href="https://colab.research.google.com/github/Bahodir01I/Data_Science-darslarim/blob/main/2_1_3_Sorting_Linear_Alg_Fayllar_b-n_ish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

**Sorting** tartiblash

In [2]:
arr = np.random.randn(6)
arr

array([-1.10125663,  1.08138625,  0.35671828,  0.46768524,  1.42992169,
       -0.20017196])

**sort** funksiyasi

In [5]:
## 1 -usul
sorted_array = np.sort(arr)
sorted_array

array([-1.10125663, -0.20017196,  0.35671828,  0.46768524,  1.08138625,
        1.42992169])

In [7]:
## 2 -usul
arr.sort()
arr

array([-1.10125663, -0.20017196,  0.35671828,  0.46768524,  1.08138625,
        1.42992169])

In [8]:
## teskari tartiblash
rev_sort = -np.sort(-arr)
rev_sort

array([ 1.42992169,  1.08138625,  0.46768524,  0.35671828, -0.20017196,
       -1.10125663])

In [9]:
## 2 d array (massiv)
arr2d = np.random.randn(4, 2)
arr2d

array([[-0.25064299,  0.62313103],
       [ 0.81024719, -1.01061096],
       [-1.00230505,  1.44685748],
       [ 0.12440861, -0.67471551]])

In [10]:
## axis = 0 >> Qator bo'yicha sortlash
row_sort = np.sort(arr2d, axis=0)
row_sort

array([[-1.00230505, -1.01061096],
       [-0.25064299, -0.67471551],
       [ 0.12440861,  0.62313103],
       [ 0.81024719,  1.44685748]])

In [11]:
## axis = 1 >> Ustun bo'yicha sortlash

col_srt = np.sort(arr2d, axis=1)
col_srt

array([[-0.25064299,  0.62313103],
       [-1.01061096,  0.81024719],
       [-1.00230505,  1.44685748],
       [-0.67471551,  0.12440861]])

## **unique** , **in1d** va **setdiif1d** metodlari

In [4]:
#data

names = np.array(['Sarvar', 'Abdurahmon', 'Hasan', 'Temur', 'Sarvar', 'Temur'])
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])


In [5]:
#unique

np.unique(names) ## bu takrorlanmas namesdagi elementlarni qaytaradi

array(['Abdurahmon', 'Hasan', 'Sarvar', 'Temur'], dtype='<U10')

In [7]:
set(names) ## bu ham unique elementlarni qaytaradi

{np.str_('Abdurahmon'), np.str_('Hasan'), np.str_('Sarvar'), np.str_('Temur')}

**in1d** usuli

In [8]:
#data

arr1 = np.array([6, 0, 0, 3, 2, 5, 6])
arr2 = np.array([0, 2, 3])

In [9]:
np.in1d(arr1, arr2) ## arr2 dagi elementlarni arr1 da borligini tekshiradi

/tmp/ipython-input-204/3141298059.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(arr1, arr2)


array([False,  True,  True,  True,  True, False, False])

**setdiff1d** usuli

In [10]:
names1 = np.array(['Jasur', 'Abdurahmon', 'Hasan', 'Muhammad', 'Sarvar', 'Temur'])
names2 = np.array(['Sarvar', 'Abdurahmon', 'Hasan', 'Temur', 'Sarvar', 'Temur'])

In [11]:
np.setdiff1d(names1, names2)

array(['Jasur', 'Muhammad'], dtype='<U10')

In [13]:
np.intersect1d(names1, names2)  # bu intersect1d esa aksincha ikklasida borlarini chiqaradi

array(['Abdurahmon', 'Hasan', 'Sarvar', 'Temur'], dtype='<U10')

## Faylaar bilan ishlash

In [17]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
np.save('data', arr)

In [20]:
arr2 = np.load('data.npy')
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
arr1 = np.arange(30)

In [24]:
np.savez('arrays.npz', a=arr, b=arr1)

In [25]:
arrays = np.load('arrays.npz')

In [27]:
arrays['a']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
np.savez_compressed('array_comp.npz', a=arr, b=arr1)

### Chiziqli algebra

In [30]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [31]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
y = np.array([[4., 4., 4.], [6., 6., 6.]])

In [33]:
y

array([[4., 4., 4.],
       [6., 6., 6.]])

In [34]:
x+y

array([[ 5.,  6.,  7.],
       [10., 11., 12.]])

In [35]:
y-x

array([[3., 2., 1.],
       [2., 1., 0.]])

In [36]:
x*4

array([[ 4.,  8., 12.],
       [16., 20., 24.]])

In [37]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
y = np.array([[6., 24.], [4., 6.], [8., -40.]])
y

array([[  6.,  24.],
       [  4.,   6.],
       [  8., -40.]])

In [39]:
x.dot(y) # bu degani x*y

array([[  38.,  -84.],
       [  92., -114.]])

In [40]:
np.dot(x, y)

array([[  38.,  -84.],
       [  92., -114.]])

In [41]:
y.dot(x)

array([[ 102.,  132.,  162.],
       [  28.,   38.,   48.],
       [-152., -184., -216.]])

In [42]:
np.dot(y, x)

array([[ 102.,  132.,  162.],
       [  28.,   38.,   48.],
       [-152., -184., -216.]])

In [43]:
## Linear Algebra
from numpy.linalg import inv