<a href="https://colab.research.google.com/github/Bahodir01I/Data_Science-darslarim/blob/main/2_1_3_Arr_Or_Pr_1_Logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Mantiqiy shart operatorlarni massiv operator sifatida qo'llash

### Shart operatori sifatida `where` dan foydalanish

### Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: `xarr` va `yarr`. Agarda shart `True`ni qanoatlantirsa `xarr` elementini qabul qilgan aksincha esa `yarr` elementini qabul qilgan yangi massiv hosil qilinsin.

In [2]:
# Massivlar yaratib olamiz
xarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5, 2.6]) # xarr
yarr = np.array([4.1, 4.2, 4.3, 4.4, 4.5, 4.6]) # yarr

In [4]:
# Shart operatirini ishlatish
condition = np.array([True, False, True, False, True, True])

In [6]:
natija = np.where(condition, xarr, yarr) ## where shart operati : agar result == True b/sa : xarr, aks holda yarrr
natija

array([2.1, 4.2, 2.3, 4.4, 2.5, 2.6])

In [7]:
array = np.random.randn(6, 6) ## 6, 6 taxminiy qiymat yaratish
array

array([[ 0.01586559, -0.4874995 , -0.13101862, -1.08950113, -0.45611788,
         1.3771164 ],
       [-0.00588896, -0.8645624 , -1.75749479,  0.03242317,  1.42440648,
         0.20118394],
       [-1.52455255, -0.71142305,  0.52221993, -1.2089911 , -2.31106028,
         0.28656074],
       [-1.34076892,  0.11473039,  0.50733186, -0.31368035, -0.93879999,
        -1.42747037],
       [-0.45624642, -1.42416626, -1.19091102, -0.45612682, -0.81240841,
         0.50730071],
       [ 1.08152102,  0.11717866, -0.40471024,  0.81264606,  0.65399874,
         0.47706012]])

In [8]:
## where
natija = np.where(array < 0, 6, -6)
natija

array([[-6,  6,  6,  6,  6, -6],
       [ 6,  6,  6, -6, -6, -6],
       [ 6,  6, -6,  6,  6, -6],
       [ 6, -6, -6,  6,  6,  6],
       [ 6,  6,  6,  6,  6, -6],
       [-6, -6,  6, -6, -6, -6]])