<a href="https://colab.research.google.com/github/Bahodir01I/Data_Science-darslarim/blob/main/2_1_3_Matematik_Statistik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np

In [27]:
data = np.random.randn(6, 4)

In [28]:
data


array([[ 0.79054074,  1.67232854, -0.23982183, -1.63141445],
       [ 0.16598878,  0.76285875, -0.19657975,  0.03047101],
       [ 1.02386016,  1.04618221, -0.1638972 , -2.74368505],
       [ 0.47004653, -1.51675888,  1.90676252,  1.0214457 ],
       [ 1.29710538,  0.98098642,  1.14703663,  1.09110581],
       [-1.36751908, -0.04271277,  0.530921  , -0.86117375]])

**sum** metodidan foydalanish

In [29]:
data.sum() ## birinchi usul

np.float64(5.1740774156412686)

In [30]:
np.sum(data) ## ikkinchi usul

np.float64(5.1740774156412686)

In [31]:
data.sum(axis=1) ## bu qator bo'yicha yig'indi

array([ 0.591633  ,  0.7627388 , -0.83753988,  1.88149586,  4.51623425,
       -1.74048461])

In [32]:
data.sum(axis=0) ## bu esa ustun bo'yicha yig'indini beradi

array([ 2.38002252,  2.90288426,  2.98442137, -3.09325073])

**mean** metodi

In [33]:
## misol uchun
data1 = np.arange(10)
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
mean = np.sum(data1)/len(data1)
mean

np.float64(4.5)

In [35]:
## numpy mean da esa
np.mean(data1)

np.float64(4.5)

In [36]:
data1.mean() ## bu ham boshqa bir usul

np.float64(4.5)

In [37]:
data

array([[ 0.79054074,  1.67232854, -0.23982183, -1.63141445],
       [ 0.16598878,  0.76285875, -0.19657975,  0.03047101],
       [ 1.02386016,  1.04618221, -0.1638972 , -2.74368505],
       [ 0.47004653, -1.51675888,  1.90676252,  1.0214457 ],
       [ 1.29710538,  0.98098642,  1.14703663,  1.09110581],
       [-1.36751908, -0.04271277,  0.530921  , -0.86117375]])

In [38]:
np.mean(data) ## bu datadagi barcha elementlarning o'rtacha qiymati

np.float64(0.21558655898505286)

In [40]:
np.mean(data, axis=1)

array([ 0.14790825,  0.1906847 , -0.20938497,  0.47037396,  1.12905856,
       -0.43512115])

In [41]:
np.mean(data, axis=0)

array([ 0.39667042,  0.48381404,  0.49740356, -0.51554179])

In [42]:
data.mean(axis=0)

array([ 0.39667042,  0.48381404,  0.49740356, -0.51554179])

**cumsum** metodi

In [45]:
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
data1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [47]:
np.cumsum(data1)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])