<a href="https://colab.research.google.com/github/Bahodir01I/Data_Science-darslarim/blob/main/2_1_3_Arifmetic_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
#data
array1 =  np.arange(12).reshape(3, 4)
array2 = np.arange(12, 24).reshape(3, 4)

In [10]:
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
array2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
#Ko'paytiramiz
array1 * array2 ## array1 ning elementlarini array2 ninig elementlariga mos ravishda ko'paytirib beraadi

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [13]:
# Bo'lish
array2 / array1   ## array2 ning elementlarini array1 ninig elementlariga mos ravishda bo'lib beraadi

/tmp/ipython-input-1048001308.py:2: RuntimeWarning: divide by zero encountered in divide
  array2 / array1   ## array2 ning elementlarini array1 ninig elementlariga mos ravishda bo'lib beraadi


array([[        inf, 13.        ,  7.        ,  5.        ],
       [ 4.        ,  3.4       ,  3.        ,  2.71428571],
       [ 2.5       ,  2.33333333,  2.2       ,  2.09090909]])

In [14]:
# qo'shish
array1  + array2 ## array1 ning elementlarini array2 ninig elementlariga mos ravishda qo'shib beraadi

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [16]:
# ayirish
array2 - array1 ## array2 ning elementlarini array1 ninig elementlarini mos ravishda ayirish

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [17]:
## kvadratga oshirish (square)
array1 ** 4

array([[    0,     1,    16,    81],
       [  256,   625,  1296,  2401],
       [ 4096,  6561, 10000, 14641]])

In [19]:
## kavdarat ildiz (sqrt)
array2**0.5

array([[3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])