<a href="https://colab.research.google.com/github/Bahodir01I/Data_Science-darslarim/blob/main/4_Boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
![Imgur](https://i.imgur.com/5pXzCIu.png)

/bin/bash: -c: line 1: syntax error near unexpected token `https://i.imgur.com/5pXzCIu.png'
/bin/bash: -c: line 1: `[Imgur](https://i.imgur.com/5pXzCIu.png)'


# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili.
## 2.1. NumPy kutubxonasi bilan ishlash

In [4]:
import numpy as np

### 2.1.1. N-o'lchamli massiv (array)larga ishlov berish

### Bolean Indekslash

In [5]:
## Ismlar
names = np.array(['Hasan', 'Husan', 'Bahodir', 'Bilolxon', 'Bositxon', 'Abdulhay', 'Dovudxon'])
names

array(['Hasan', 'Husan', 'Bahodir', 'Bilolxon', 'Bositxon', 'Abdulhay',
       'Dovudxon'], dtype='<U8')

In [6]:
## data

data = np.random.randn(7, 4)
data

array([[ 1.09893416,  0.52777563, -1.75991513,  0.64298318],
       [ 0.59357618,  0.24588377, -1.70471453,  0.17060279],
       [-1.44174833, -0.36895594, -0.84274523, -2.38670936],
       [-0.18365724,  1.05377127, -0.71393932,  1.61454157],
       [ 0.45710142, -0.58819898,  0.7400524 ,  1.03330366],
       [ 0.31949841,  0.10781636, -0.99776231, -0.99831293],
       [ 0.73810045, -0.44214832,  0.53891652,  0.39876048]])

In [7]:
names == 'Bahodir'

array([False, False,  True, False, False, False, False])

In [8]:
data[names == 'Bahodir']  ## Bahodirga tegishli barcha ma'lumotlarni ajratib olish

array([[-1.44174833, -0.36895594, -0.84274523, -2.38670936]])

In [9]:
data[names == 'Bositxon'] ## Bositxonga tegishli barcha ma'lumotlarnin ajratib olish

array([[ 0.45710142, -0.58819898,  0.7400524 ,  1.03330366]])

In [10]:
data[names=='Bahodir', 2:] # Bahodirga tegishli oxirgi ikkita ustundagi ma'lumotlarni ajratib olish

array([[-0.84274523, -2.38670936]])

In [11]:
data[names !='Bahodir']  ## (!=) Bahodirdan tashqari qolgan barcha insonlarni ma'lumotlarini chop qilish

array([[ 1.09893416,  0.52777563, -1.75991513,  0.64298318],
       [ 0.59357618,  0.24588377, -1.70471453,  0.17060279],
       [-0.18365724,  1.05377127, -0.71393932,  1.61454157],
       [ 0.45710142, -0.58819898,  0.7400524 ,  1.03330366],
       [ 0.31949841,  0.10781636, -0.99776231, -0.99831293],
       [ 0.73810045, -0.44214832,  0.53891652,  0.39876048]])

In [12]:
data[~(names =='Bahodir')] ## (~) bu ham yuqoridagi cell bilan bir xil natijani chiqaradi

array([[ 1.09893416,  0.52777563, -1.75991513,  0.64298318],
       [ 0.59357618,  0.24588377, -1.70471453,  0.17060279],
       [-0.18365724,  1.05377127, -0.71393932,  1.61454157],
       [ 0.45710142, -0.58819898,  0.7400524 ,  1.03330366],
       [ 0.31949841,  0.10781636, -0.99776231, -0.99831293],
       [ 0.73810045, -0.44214832,  0.53891652,  0.39876048]])

In [15]:
print(names)

['Hasan' 'Husan' 'Bahodir' 'Bilolxon' 'Bositxon' 'Abdulhay' 'Dovudxon']


In [16]:
print(data)

[[ 1.09893416  0.52777563 -1.75991513  0.64298318]
 [ 0.59357618  0.24588377 -1.70471453  0.17060279]
 [-1.44174833 -0.36895594 -0.84274523 -2.38670936]
 [-0.18365724  1.05377127 -0.71393932  1.61454157]
 [ 0.45710142 -0.58819898  0.7400524   1.03330366]
 [ 0.31949841  0.10781636 -0.99776231 -0.99831293]
 [ 0.73810045 -0.44214832  0.53891652  0.39876048]]


In [20]:
mask = (names == 'Bahodir') | (names == 'Bositxon') ## "|" or (yoki) -- bu belgi belgisini ifodalaydi

In [21]:
mask

array([False, False,  True, False,  True, False, False])

In [22]:
data[mask]  ## Bahodir va Bositxonlarga tegishli ma'lumotlarni ajratib olish

array([[-1.44174833, -0.36895594, -0.84274523, -2.38670936],
       [ 0.45710142, -0.58819898,  0.7400524 ,  1.03330366]])

In [23]:
data

array([[ 1.09893416,  0.52777563, -1.75991513,  0.64298318],
       [ 0.59357618,  0.24588377, -1.70471453,  0.17060279],
       [-1.44174833, -0.36895594, -0.84274523, -2.38670936],
       [-0.18365724,  1.05377127, -0.71393932,  1.61454157],
       [ 0.45710142, -0.58819898,  0.7400524 ,  1.03330366],
       [ 0.31949841,  0.10781636, -0.99776231, -0.99831293],
       [ 0.73810045, -0.44214832,  0.53891652,  0.39876048]])

In [24]:
data[data<0]

array([-1.75991513, -1.70471453, -1.44174833, -0.36895594, -0.84274523,
       -2.38670936, -0.18365724, -0.71393932, -0.58819898, -0.99776231,
       -0.99831293, -0.44214832])

In [25]:
data[data<0] = 0

In [26]:
data

array([[1.09893416, 0.52777563, 0.        , 0.64298318],
       [0.59357618, 0.24588377, 0.        , 0.17060279],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.05377127, 0.        , 1.61454157],
       [0.45710142, 0.        , 0.7400524 , 1.03330366],
       [0.31949841, 0.10781636, 0.        , 0.        ],
       [0.73810045, 0.        , 0.53891652, 0.39876048]])

## Xulosa o'rnida aytganimzda boolean indexlash - bu bizga massivlarninig bir qancha ma'lumotlar ustida bir vaqtning o'zida turli xil ammalarni bajarish imkoniyatini beradi